[env:esp32-c3]
platform = espressif32
board = adafruit_qtpy_esp32c3
framework = arduino

monitor_speed = 115200
monitor_port = /dev/ttyACM0

upload_speed = 921600
upload_port = /dev/ttyACM0

build_flags = 
	-DARDUINO_USB_CDC_ON_BOOT=1
	-DCORE_DEBUG_LEVEL=0

board_build.filesystem = littlefs

lib_deps =
    olikraus/U8g2
    ricmoo/QRCode@^0.0.1